### ISSUE TITLE
Allow parsing webpage into a single block in order to make it usable for other plugins

### ISSUE THREAD

**Issue by teun95** [sawhney17/logseq-web-parser#10]
logseq-summarizer is only able to deal with a single block. There are or will be more plugins with limitations like this. It would be useful to have to option to import and parse a website's content into a single block in order to immediately be able to call another plugin with a command without needing to transform the imported text.

**Comment by sawhney17** [comment]
Latest version offers hits feature. you can use "Parse URL as single block"
