### ISSUE TITLE
Parse URL command should parse markdown-formatted URLs

### ISSUE THREAD

**Issue by mkosma** [sawhney17/logseq-web-parser#8]
Parse URL doesn't work on URLs formatted like [title][url) ... seems like that shouldn't be too hard. 

Does the current code require that the URL is basically the only thing in a block? Haven't pushed it too hard to see what it would do, outside of this one case.

**Comment by sawhney17** [comment]
Should be fixed ink the new version

**Comment by mkosma** [comment]
sweet! thanks!
